import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Navigation } from "@/components/navigation";
import { Sidebar } from "@/components/sidebar";
import { Providers } from "@/components/providers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "kvernhaug's trusty homepage",
  description: "Generated by magic faeries",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>  
      <body>
        <Providers>
          <div className="flex items-center flex-col bg-autumn bg-cover w-screen h-screen">
            <div className="flex w-1/2 h-1/5"></div>
            <div // Center background banner (orange)
              className="flex flex-col bg-neutral-300 bg-opacity-70 w-2/3 h-screen rounded-t-2xl"
            >
              <nav className="">
                <Navigation />
              </nav>
              <main className="flex flex-row">
                <div className="flex-1">
                  {children}
                </div>
              </main>
            </div>
          </div>
        </Providers>
      </body>
    </html >
  );
}
